### ISSUE TITLE
Question: Possible for change color (of TEXT?)

### ISSUE THREAD

**Issue by mrc4tt** [qubka/Zombie-Plague#1]
Hi.

I will hear, about it's possible to change color SAY?

From WHITE to RED as example?

**Comment by qubka** [comment]
Probably yes you can, just need to hook chat message and block it, after reformat insing color you want, you can look how colors work in the zp core and apply in your plugin. 

**That might help you maybe:**
```
https://forums.alliedmods.net/showthread.php?t=96831?t=96831
https://forums.alliedmods.net/showthread.php?t=94187?t=94187
```

_Good luck!_
Nikit Ushakov
