### ISSUE TITLE
crash server with last version sourcemod 1.9

### ISSUE THREAD

**Issue by Drmohammad11** [qubka/Zombie-Plague#2]
**Describe the bug**

crash server with last version sourcemod 1.9

**To Reproduce**
1. Install zombie plugin 8.4.9 with sourcemod 1.9-git6261, dhooks-2.2.0-hg126-windows and metamod:source 1.11 - build 1116
2. start server

**Expected behavior:**

start my server without crash and dump

**Log -condbug:**

`
L 11/27/2018 - 08:14:19: [zbm3_core.smx] [Config] [Map Configs] Executed main config file: "cfg/sourcemod/zombieplague.cfg"
L 11/27/2018 - 08:14:19: [zbm3_core.smx] [Sounds] [Config Validation] Loading sounds from file "addons\sourcemod\zombieplague\sounds.ini"
L 11/27/2018 - 08:14:19: [zbm3_core.smx] [Sounds] [Config Validation] Total blocks: 127 | Unsuccessful blocks: 0 | Total: 290 | Successful: 290 | Unsuccessful: 0
Here Cerashed My Server.....
`

**Desktop (please complete the following information):**

 - OS: windows server 2012 r2
 - SM: 1.9-git6162
 - DHooks: 2.2.0-hg126
 - Metamod:Sourcemod: 1.11-build1116

**Comment by qubka** [comment]
May be some signatures or offsets are wrong, i am not able to test mod on the windows platform, if you have time to test, find me in discord, i will try to fix issue and you will test it. My discord: qubka#9792

**Comment by Drmohammad11** [comment]
hi friend.
i can not help you because i bad speak english and i don't have discord.

i am sorry :(
