### ISSUE TITLE
How to remove Smoke and HE grenade on round start ?

### ISSUE THREAD

**Issue by abhishekdeshkar** [qubka/Zombie-Plague#4]
Hello,

How do I disable HE grenade and Smoke grenade at the beginning of round ?  HE Grenade and Smoke grenade should be added after one zombie is selected. I tried to find in the code but couldn't find it.

**Comment by qubka** [comment]
Please read the topic, everything is there, you should remove them from the weapon block for each class in classes.ini ( each class have own default weapon on the start)
